// Dallas College programs of study for the Q2 picker.
//
// Generated from the 2026-2027 catalog program pages (acalog preview_program).
// `code` is the catalog program id (poid); it is a stable, real identifier that
// maps one-to-one to a catalog program until canonical program codes are wired in
// from catalog ingestion. Regenerate from the catalog when it refreshes.

export interface Program {
  code: string;
  label: string;
}

export const PROGRAMS: Program[] = [
  { code: "2760", label: "A+ Occupational Skills Award" },
  { code: "2761", label: "Accounting A.A.S." },
  { code: "2762", label: "Accounting Assistant Certificate" },
  { code: "2763", label: "Accounting Clerk Certificate" },
  { code: "2764", label: "Administrative Certificate" },
  { code: "2766", label: "Administrative Specialist Certificate" },
  { code: "2767", label: "Adult Cardiac Sonography A.A.S." },
  { code: "2769", label: "Advanced Architectural Drafting Certificate" },
  { code: "2770", label: "Advanced Mechanical Drafting Certificate" },
  { code: "2970", label: "Advanced Technical Certificate in Professional Accountancy" },
  { code: "2771", label: "Air Conditioning and Refrigeration Technology A.A.S." },
  { code: "3174", label: "Alteration Specialist Certificate" },
  { code: "2774", label: "Animation Certificate" },
  { code: "2775", label: "Apparel Design A.A.S." },
  { code: "2776", label: "Architectural Drafting Certificate" },
  { code: "2777", label: "Architectural Drafting Occupational Skills Award" },
  { code: "2779", label: "Associate Degree Nursing A.A.S." },
  { code: "3393", label: "Associate of Arts A.A." },
  { code: "3448", label: "Associate of Science A.S." },
  { code: "2782", label: "Audio Visual Specialist Certificate" },
  { code: "2783", label: "Auto Body Metal Technician Certificate" },
  { code: "3165", label: "Auto Body Metal Technician Occupational Skills Award" },
  { code: "2784", label: "Auto Body Painter Certificate" },
  { code: "3166", label: "Auto Body Painter Occupational Skills Award" },
  { code: "3130", label: "Auto Body Shop Management Certificate" },
  { code: "3167", label: "Auto Body Shop Management Occupational Skills Award" },
  { code: "2785", label: "Auto Body Technology A.A.S." },
  { code: "2786", label: "Auto Body Technology Certificate" },
  { code: "2946", label: "Automotive Career Technician A.A.S." },
  { code: "3028", label: "Bachelor of Applied Science in Early Childhood Education and Teaching" },
  { code: "3791", label: "Bachelor of Applied Science in Management" },
  { code: "3381", label: "Bachelor of Applied Technology in Software Development" },
  { code: "2787", label: "Bakery/Pastry A.A.S." },
  { code: "2788", label: "Bakery/Pastry Foundations Certificate" },
  { code: "2789", label: "Bakery/Pastry Specialist Certificate" },
  { code: "2790", label: "Basic Criminal Justice Studies Certificate" },
  { code: "3199", label: "Basic Firefighter Certificate" },
  { code: "3389", label: "Behavioral Health Management Advanced Technical Certificate" },
  { code: "3162", label: "Biotechnology Certificate" },
  { code: "3382", label: "Blockchain Occupational Skills Award" },
  { code: "2960", label: "Builder/Contractor Certificate" },
  { code: "2794", label: "Business Administration A.A.S." },
  { code: "2798", label: "Business Office Specialist Certificate" },
  { code: "2799", label: "Business Operations Generalist Certificate" },
  { code: "2800", label: "Business Operations Specialist Certificate" },
  { code: "2801", label: "C# Developer Certificate" },
  { code: "2802", label: "C# Programming Occupational Skills Award" },
  { code: "2803", label: "C++ Developer Certificate" },
  { code: "2804", label: "C++ Programming Occupational Skills Award" },
  { code: "2808", label: "Chassis Service Technician Certificate" },
  { code: "3194", label: "Chassis Service Technician Occupational Skills Award" },
  { code: "2810", label: "Child Development/Early Childhood Education A.A.S." },
  { code: "2811", label: "CISCO Networking CCNA Occupational Skills Award" },
  { code: "2813", label: "Civil Drafting Certificate" },
  { code: "2814", label: "Civil Drafting Occupational Skills Award" },
  { code: "2816", label: "Cloud Computing A.A.S." },
  { code: "2817", label: "Cloud Computing Certificate" },
  { code: "2818", label: "Cloud Computing Occupational Skills Award" },
  { code: "2819", label: "Cloud System Operations A.A.S." },
  { code: "2820", label: "CNC Mill and Lathe Operator Certificate" },
  { code: "2821", label: "CNC Mill and Lathe Operator Occupational Skills Award" },
  { code: "2822", label: "Commercial Construction Assistant Superintendent Certificate" },
  { code: "2823", label: "Commercial Construction Certificate" },
  { code: "2824", label: "Commercial Electrical Technology A.A.S." },
  { code: "2825", label: "Commercial Electrical Technology Certificate" },
  { code: "3200", label: "Commercial Electrical Technology Occupational Skills Award" },
  { code: "2827", label: "Computed Tomography Advanced Technical Certificate" },
  { code: "3013", label: "Computer-Aided Design and Drafting A.A.S." },
  { code: "2924", label: "Construction Management A.A.S." },
  { code: "2925", label: "Construction Technology A.A.S." },
  { code: "3176", label: "Construction Technology Occupational Skills Award" },
  { code: "3040", label: "Core Options for A.A.S. Awards" },
  { code: "2926", label: "Credential for Critical Care Professionals Enhanced Skills Certificate" },
  { code: "2922", label: "Criminal Justice and Public Safety A.A.S." },
  { code: "2923", label: "Criminal Justice Management Certificate" },
  { code: "3009", label: "Crisis Intervention Certificate" },
  { code: "3008", label: "Culinary Arts A.A.S." },
  { code: "3007", label: "Culinary Arts Foundations Certificate" },
  { code: "3006", label: "Culinary Arts Specialist Certificate" },
  { code: "3004", label: "Customer Service Representative Certificate" },
  { code: "2892", label: "Cyber Operations Certificate" },
  { code: "3003", label: "Cyber Security A.A.S." },
  { code: "3014", label: "DBA Certificate" },
  { code: "3015", label: "Dealership-Sponsored Technician A.A.S." },
  { code: "3016", label: "Dental Hygiene A.A.S." },
  { code: "3017", label: "Designate Certificate" },
  { code: "3018", label: "Diagnostic Medical Sonography A.A.S." },
  { code: "3197", label: "Diesel Preventive Maintenance Advanced Technician Occupational Skills Award" },
  { code: "3198", label: "Diesel Preventive Maintenance Technician Occupational Skills Award" },
  { code: "3020", label: "Digital Art and Design A.A.S." },
  { code: "3021", label: "Digital Forensics and Private Investigation Certificate" },
  { code: "3022", label: "Digital Interface Design Certificate" },
  { code: "3023", label: "Digital Media Marketing Specialist Certificate" },
  { code: "3026", label: "Digital Photography/Video Certificate" },
  { code: "3029", label: "Early Childhood Education and Teaching Certificate" },
  { code: "3169", label: "Early Childhood Teacher Development Occupational Skills Award" },
  { code: "3803", label: "Electrical Construction A.A.S." },
  { code: "3802", label: "Electrical Construction Certificate" },
  { code: "3034", label: "Electrical Engineering Technology A.A.S." },
  { code: "3035", label: "Electro Mechanical Technology A.A.S." },
  { code: "3036", label: "Electronics and Climate Controls Technician Certificate" },
  { code: "3195", label: "Electronics and Climate Controls Technician Occupational Skills Award" },
  { code: "3039", label: "Electronics Technology Certificate" },
  { code: "3138", label: "Electronics Technology Occupational Skills Award" },
  { code: "2914", label: "Emergency Medical Services/Paramedic A.A.S." },
  { code: "2913", label: "Emergency Medical Technician Basic Certificate" },
  { code: "3816", label: "Endoscopy Technician Certificate" },
  { code: "2911", label: "Engine Repair and Performance Technician Certificate" },
  { code: "3193", label: "Engine Repair and Performance Technician Occupational Skills Award" },
  { code: "2912", label: "Engineering Technology Certificate" },
  { code: "2944", label: "Entrepreneurial Foundation Certificate" },
  { code: "3140", label: "Entrepreneurial Management Certificate" },
  { code: "3141", label: "Entrepreneurship A.A.S." },
  { code: "2908", label: "Equine Clinical Skills Enhanced Skills Certificate" },
  { code: "2909", label: "Executive Assistant A.A.S." },
  { code: "2910", label: "Experience Design/User Interface (UX/UI) A.A.S." },
  { code: "3380", label: "Extended Reality (XR) Certificate" },
  { code: "3206", label: "FAME Manufacturing Core Exercises Enhanced Skills Certificate" },
  { code: "3175", label: "Fashion Design Certificate" },
  { code: "2915", label: "Fashion Marketing A.A.S." },
  { code: "3168", label: "Film and Video Production Advanced Technical Certificate" },
  { code: "2916", label: "Financial Services Associate Certificate" },
  { code: "2917", label: "Fire Arson/Investigation Certificate" },
  { code: "2918", label: "Fire Protection Technology A.A.S." },
  { code: "2919", label: "Fire Science Certificate" },
  { code: "3001", label: "Food and Beverage Specialist Certificate" },
  { code: "3000", label: "Forensic Science Technician Certificate" },
  { code: "3806", label: "Forensics A.A.S." },
  { code: "2999", label: "Fundamentals of Information Technology Skills Achievement Award" },
  { code: "2998", label: "Game Development Certificate" },
  { code: "2997", label: "Gas Metal Arc Welding (GMAW) Certificate" },
  { code: "3186", label: "Gas Metal Arc Welding (GMAW) Occupational Skills Award" },
  { code: "2996", label: "Gas Tungsten Arc Welding (GTAW) Certificate" },
  { code: "3187", label: "Gas Tungsten Arc Welding (GTAW) Occupational Skills Award" },
  { code: "2995", label: "Geographic Information Systems Specialist A.A.S." },
  { code: "3189", label: "Geographic Information Systems Technician Advanced Technical Certificate" },
  { code: "3190", label: "Geographic Information Systems Technician Certificate (C1)" },
  { code: "2994", label: "Geographic Information Systems Technician Certificate (C2)" },
  { code: "3188", label: "Geographic Information Systems Technology Occupational Skills Award" },
  { code: "2993", label: "Gerontology Certificate" },
  { code: "2904", label: "Global Trade Specialist Certificate" },
  { code: "2992", label: "Google IT Professional Occupational Skills Award" },
  { code: "2991", label: "Health Information Technology A.A.S." },
  { code: "2990", label: "Health Information Technology Medical Coder Certificate" },
  { code: "2989", label: "Health Professions Readiness I Skills Achievement Award" },
  { code: "2988", label: "Health Professions Readiness II Skills Achievement Award" },
  { code: "3159", label: "Heating and Air Conditioning Occupational Skills Award" },
  { code: "2987", label: "Help Desk/User Support Technician Certificate" },
  { code: "2986", label: "High Performance Modification Certificate" },
  { code: "2898", label: "Honda Professional Automotive Career Training A.A.S." },
  { code: "2899", label: "Hospitality Management A.A.S." },
  { code: "3154", label: "Hospitality Management Certificate" },
  { code: "3149", label: "Hotel Lodging Operations Certificate" },
  { code: "2900", label: "Human Resources Assistant Certificate" },
  { code: "2901", label: "Human Resources Associate Certificate" },
  { code: "2902", label: "Human Resources Management A.A.S." },
  { code: "2903", label: "Human Services Certificate" },
  { code: "2905", label: "Industrial Automation Certificate" },
  { code: "3153", label: "Industrial Automation Occupational Skills Award" },
  { code: "2893", label: "Information Security Occupational Skills Award" },
  { code: "2894", label: "Information Systems Administration Foundations Certificate" },
  { code: "2897", label: "Interactive Simulation and Game Technology A.A.S." },
  { code: "2885", label: "Interior Design A.A.S." },
  { code: "3386", label: "Interior Design Foundational Certificate" },
  { code: "3385", label: "Interior Design Micro-Credential Advanced Technical Certificate" },
  { code: "2887", label: "International Business and Trade A.A.S." },
  { code: "2888", label: "International Business and Trade Certificate" },
  { code: "2889", label: "International Business and Trade Skills Achievement Award" },
  { code: "3383", label: "Intro to Data Analytics Occupational Skills Award" },
  { code: "2890", label: "Invasive Cardiovascular Technology A.A.S." },
  { code: "2879", label: "Invasive Cardiovascular Technology Advanced Technical Certificate" },
  { code: "2880", label: "Java Developer Certificate" },
  { code: "2881", label: "Java Programming Occupational Skills Award" },
  { code: "3164", label: "Junior Legal Assistant Certificate" },
  { code: "2882", label: "Land Surveying and Geospatial Technology A.A.S." },
  { code: "2883", label: "Land Surveying Certificate" },
  { code: "2884", label: "Leadership Occupational Skills Award" },
  { code: "2872", label: "LINUX Skills Achievement Award" },
  { code: "3789", label: "Live Sound Certificate" },
  { code: "2873", label: "Logistics and Supply Chain Management A.A.S." },
  { code: "2874", label: "Logistics Distribution Technician Certificate" },
  { code: "2875", label: "Logistics Distribution Technician Occupational Skills Award" },
  { code: "2876", label: "Magnetic Resonance Imaging Advanced Technical Certificate" },
  { code: "3787", label: "Magnetic Resonance Imaging Technologist A.A.S." },
  { code: "2877", label: "Management A.A.S." },
  { code: "2878", label: "Management Certificate" },
  { code: "2797", label: "Marketing A.A.S." },
  { code: "2866", label: "Mechanical Drafting Certificate" },
  { code: "2867", label: "Mechanical Drafting Occupational Skills Award" },
  { code: "2870", label: "Mechatronics Technology Certificate" },
  { code: "3139", label: "Mechatronics Technology Occupational Skills Award" },
  { code: "2871", label: "Medical Assisting Certificate" },
  { code: "2859", label: "Medical Assisting Generalist Certificate" },
  { code: "2860", label: "Medical Front Office Assistant Certificate" },
  { code: "2861", label: "Medical Front Office Assistant Occupational Skills Award" },
  { code: "2862", label: "Medical Laboratory Technology A.A.S." },
  { code: "2807", label: "Meeting and Events Professional Certificate" },
  { code: "2863", label: "Mental Health/Substance Abuse Prevention Certificate" },
  { code: "2852", label: "Mobile Applications Occupational Skills Award" },
  { code: "2853", label: "Mortgage Banking A.A.S." },
  { code: "2854", label: "Mortgage Banking Intern Certificate" },
  { code: "3180", label: "Multiple Processes Welding Occupational Skills Award" },
  { code: "2857", label: "Music Business and Entrepreneurship A.A.S." },
  { code: "2858", label: "Music Business and Entrepreneurship Certificate" },
  { code: "2845", label: "Network Administrator and Support A.A.S." },
  { code: "2846", label: "Networking Associate Certificate" },
  { code: "2849", label: "Networking Support Certificate" },
  { code: "2850", label: "Networking Virtualization Skills Achievement Award" },
  { code: "3797", label: "NTE (North Texas Electrical) Journeyman Electrician 1 Occupational Skills Award" },
  { code: "3798", label: "NTE (North Texas Electrical) Journeyman Electrician 2 Occupational Skills Award" },
  { code: "3799", label: "NTE (North Texas Electrical) Journeyman Electrician 3 Occupational Skills Award" },
  { code: "3800", label: "NTE (North Texas Electrical) Journeyman Electrician 4 Occupational Skills Award" },
  { code: "3801", label: "NTE (North Texas Electrical) Journeyman Electrician 5 Occupational Skills Award" },
  { code: "3790", label: "Occupational Skills Award in Professional Accountancy" },
  { code: "2985", label: "Occupational Therapy Assistant A.A.S." },
  { code: "2984", label: "Paralegal A.A.S." },
  { code: "2983", label: "Paramedic Certificate" },
  { code: "2981", label: "Patient Care Technician Certificate" },
  { code: "2978", label: "Performing Musician A.A.S." },
  { code: "2977", label: "Performing Musician Certificate" },
  { code: "2975", label: "Personal Computer Support A.A.S." },
  { code: "3784", label: "Piano Tuning and Field Service Certificate" },
  { code: "3181", label: "Pipe Welding and Fitting Occupational Skills Award" },
  { code: "3155", label: "Plumbing Technology A.A.S." },
  { code: "3156", label: "Plumbing Technology Certificate" },
  { code: "3172", label: "Power Equipment Occupational Skills Award" },
  { code: "3170", label: "Power Equipment Technology Certificate" },
  { code: "3171", label: "Power Sports Certificate" },
  { code: "3173", label: "Power Sports Occupational Skills Award" },
  { code: "3808", label: "Pre-Apprenticeship Certificate in Electrical Construction Technology" },
  { code: "2973", label: "Precision Machining Technology A.A.S." },
  { code: "2971", label: "Preventive Maintenance Technician Certificate" },
  { code: "3024", label: "Producer and Songwriter A.A.S." },
  { code: "3025", label: "Producer Certificate" },
  { code: "3161", label: "Psychiatric Technician Certificate" },
  { code: "2968", label: "Python Developer Certificate" },
  { code: "2967", label: "Python Programming Occupational Skills Award" },
  { code: "2966", label: "Radiologic Technology A.A.S." },
  { code: "2965", label: "Real Estate A.A.S." },
  { code: "2964", label: "Real Estate Certificate" },
  { code: "3163", label: "Real Estate Certificate II" },
  { code: "2963", label: "Recording Technology A.A.S." },
  { code: "2961", label: "Recording Technology Certificate (One-Year Certificate)" },
  { code: "2962", label: "Recording Technology Level II Certificate" },
  { code: "3157", label: "Registered Nurse to Bachelor of Science in Nursing" },
  { code: "2957", label: "Respiratory Care A.A.S." },
  { code: "2956", label: "Retail Management Certificate" },
  { code: "2958", label: "Rising Builder Occupational Skills Award" },
  { code: "3178", label: "Rising Construction Manager Certificate" },
  { code: "3179", label: "Rising Construction Manager Occupational Skills Award" },
  { code: "3177", label: "Rising Construction Technology Occupational Skills Award" },
  { code: "2955", label: "Rising Electrical Technician Certificate" },
  { code: "2954", label: "Rising Electrical Technician Occupational Skills Award" },
  { code: "2953", label: "Rising HVAC Technician Certificate" },
  { code: "3160", label: "Rising HVAC Technician Occupational Skills Award" },
  { code: "2952", label: "Rising Land Surveyor Certificate" },
  { code: "2951", label: "Rising Plumber Certificate" },
  { code: "3151", label: "Rising Plumber Occupational Skills Award" },
  { code: "2950", label: "Rising Welder Certificate" },
  { code: "3182", label: "Rising Welder Occupational Skills Award" },
  { code: "2949", label: "Robotics and Industrial Automation A.A.S." },
  { code: "2948", label: "Sales and Marketing Professional Certificate" },
  { code: "2945", label: "Shielded Metal Arc Welding (SMAW) Certificate" },
  { code: "3183", label: "Shielded Metal Arc Welding (SMAW) Occupational Skills Award" },
  { code: "3379", label: "Simulation Operations Specialist Advanced Technical Certificate" },
  { code: "2942", label: "Social Work Associate - Generalist A.A.S." },
  { code: "2940", label: "Software Application Specialist Certificate" },
  { code: "2939", label: "Software Development A.A.S." },
  { code: "2826", label: "Songwriter Certificate" },
  { code: "2937", label: "SQL Occupational Skills Award" },
  { code: "2936", label: "Structural Welding Certificate" },
  { code: "3184", label: "Structural Welding Occupational Skills Award" },
  { code: "2935", label: "Substance Abuse Counseling A.A.S." },
  { code: "2934", label: "Substance Abuse Counseling Certificate" },
  { code: "2933", label: "Supervisor Certificate" },
  { code: "2932", label: "Surgical Technologist A.A.S." },
  { code: "2931", label: "Surveying Occupational Skills Award" },
  { code: "2930", label: "Technical Pattern Design A.A.S." },
  { code: "2772", label: "Technician Level I Certificate in Air Conditioning" },
  { code: "2773", label: "Technician Level II Certificate in Air Conditioning" },
  { code: "3203", label: "Theatrical Construction Certificate" },
  { code: "2929", label: "Theatrical Costuming Certificate" },
  { code: "3158", label: "Theatrical Light Board Operator Certificate" },
  { code: "3201", label: "Theatrical Master Electrician Certificate" },
  { code: "3202", label: "Theatrical Sound Board Operator Certificate" },
  { code: "2928", label: "Toyota Technician-Training and Education Network A.A.S." },
  { code: "3152", label: "Tradesman Plumber Certificate" },
  { code: "2840", label: "Transmission Service Technician Certificate" },
  { code: "3196", label: "Transmission Service Technician Occupational Skills Award" },
  { code: "2806", label: "Travel and Destination Management Certificate" },
  { code: "2841", label: "UX/UI Design Certificate" },
  { code: "2842", label: "Vascular Interventional Advanced Technical Certificate" },
  { code: "2843", label: "Veterinary Assisting Certificate" },
  { code: "2844", label: "Veterinary Technology A.A.S." },
  { code: "2839", label: "Video Technology A.A.S." },
  { code: "2837", label: "Visual Design Certificate" },
  { code: "2836", label: "Visual Presentation Specialist Certificate" },
  { code: "2835", label: "Vocational Nursing Certificate" },
  { code: "2831", label: "Web Design Occupational Skills Award" },
  { code: "2832", label: "Web Developer Certificate" },
  { code: "2833", label: "Web Development A.A.S." },
  { code: "2834", label: "Web Development Certificate" },
  { code: "3185", label: "Weld Fabrication Occupational Skills Award" },
  { code: "2829", label: "Welding Applications A.A.S." },
  { code: "2830", label: "Welding Applications Certificate" },
  { code: "2828", label: "Wholesale and Manufacturing Sales Representative Certificate" },
];
