export const onboardingQuestions = [
  "What best describes you right now?",
  "What are you hoping to accomplish today?",
  "What degree, certificate, or program are you pursuing?",
  "Have you declared your major or program of study?",
  "Are you planning to transfer to a university?",
  "Have you attended another college before?",
  "Have all official transcripts been submitted to Dallas College?",
  "Do you have military, AP, CLEP, IB, or dual-credit coursework?",
  "Are you planning to attend full-time or part-time?",
  "Do you prefer online, in-person, or hybrid classes?",
  "What semester are you planning for?",
  "Have you reviewed your Academic Progress report in Workday?",
  "Have you checked your Workday account for registration holds?",
  "Have you checked your Dallas College student email recently?",
  "Do you have financial aid, payment, or scholarship questions?",
  "Are there work, childcare, transportation, or family responsibilities that may affect your class schedule?",
  "What questions do you want to ask your Success Coach?",
];
