"""
load_catalog_to_neon.py

Purpose:
    Validate Catalog and CV JSON datasets before optionally loading
    them into the Neon PostgreSQL knowledge_entry table.

Workflow:
    1. Read the JSON dataset.
    2. Validate every record.
    3. Validate the dataset composition.
    4. Convert rows into database-ready objects.
    5. Upsert the rows into Neon in configurable batches.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter
from datetime import datetime
from pathlib import Path
from typing import Any

from sqlalchemy import case, func
from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.orm import Session

from dallasai.database import SessionLocal
from dallasai.models import KnowledgeEntry


# ==========================================================
# Validation Configuration
# ==========================================================
# Expected document counts for the official catalog dataset.
CATALOG_EXPECTED_COUNTS = {
    "course": 1_588,
    "program_map": 318,
    "section": 16_181,
}

# A supplemental delivery is program_map rows only. Its expected COUNT is
# supplied by the operator with --expect, not hardcoded: the bug this mode
# fixes was a hardcoded count rejecting a valid file, so baking in a second
# number would make the mode work exactly once. Stating the expected count
# still catches a truncated or double-written file, which is the protection
# that matters.
SUPPLEMENTAL_PROGRAM_DOC_TYPE = "program_map"

# Required fields that every JSON row must contain.
REQUIRED_FIELDS = {
    "source_url",
    "chunk_index",
    "chunk_text",
    "facts",
    "metadata",
    "content_hash",
    "scraped_at",
    "embedding",
}

# Every embedding generated by the pipeline must contain
# exactly 768 dimensions.
EMBEDDING_DIMENSIONS = 768


# ==========================================================
# Helper Functions
# ==========================================================
# Converts ISO date strings into Python datetime objects.
def parse_datetime(value: str | datetime) -> datetime:
    """Convert an ISO-8601 string to a datetime object."""

    # Already converted.
    if isinstance(value, datetime):
        return value

    # Convert ISO string to datetime.
    return datetime.fromisoformat(
        value.replace("Z", "+00:00")
    )


# ==========================================================
# JSON Loading & Validation
# ==========================================================
# Reads the complete JSON dataset and validates every record
# before anything is written into Neon.
def load_rows(
    path: Path,
    *,
    allow_supplemental_programs: bool = False,
    expected_supplemental_rows: int | None = None,
) -> list[dict[str, Any]]:
    """Read and validate the complete JSON dataset."""

    # Verify that the file exists.
    if not path.exists():
        raise FileNotFoundError(
            f"JSON file was not found: {path}"
        )

    # Verify it is actually a file.
    if not path.is_file():
        raise ValueError(
            f"The supplied path is not a file: {path}"
        )

    print("Starting", flush=True)
    print(f"Opening file: {path}", flush=True)

    print(
        "Reading the complete JSON file. Please wait...",
        flush=True,
    )

    # Read the complete JSON into memory.
    with path.open("r", encoding="utf-8") as file:
        rows: list[dict[str, Any]] = json.load(file)

    print("Finished reading JSON file", flush=True)

    # Root object must be a list.
    if not isinstance(rows, list):
        raise ValueError(
            "The root JSON value must be a list."
        )

    # Dataset cannot be empty.
    if not rows:
        raise ValueError(
            "The JSON file contains no rows."
        )

    # Track document counts and duplicate keys.
    counts: Counter[str] = Counter()
    seen_keys: set[tuple[str, int]] = set()

    # Validate every JSON row.
    for index, row in enumerate(rows):

        if not isinstance(row, dict):
            raise ValueError(
                f"Row {index} is not a JSON object."
            )

        # Check required fields.
        missing_fields = REQUIRED_FIELDS - row.keys()

        if missing_fields:
            raise ValueError(
                f"Row {index} is missing required fields: "
                f"{sorted(missing_fields)}"
            )

        source_url = row["source_url"]
        chunk_index = row["chunk_index"]
        chunk_text = row["chunk_text"]
        facts = row["facts"]
        metadata = row["metadata"]
        content_hash = row["content_hash"]
        scraped_at = row["scraped_at"]
        embedding = row["embedding"]

        # Validate each field individually.
        if not isinstance(source_url, str) or not source_url.strip():
            raise ValueError(
                f"Row {index} has an invalid source_url."
            )

        if not isinstance(chunk_index, int):
            raise ValueError(
                f"Row {index} has an invalid chunk_index."
            )

        if not isinstance(chunk_text, str):
            raise ValueError(
                f"Row {index} has an invalid chunk_text."
            )

        if not isinstance(facts, dict):
            raise ValueError(
                f"Row {index} has invalid facts."
            )

        if not isinstance(metadata, dict):
            raise ValueError(
                f"Row {index} has invalid metadata."
            )

        if not isinstance(content_hash, str) or not content_hash:
            raise ValueError(
                f"Row {index} has an invalid content_hash."
            )

        try:
            parse_datetime(scraped_at)
        except (TypeError, ValueError) as error:
            raise ValueError(
                f"Row {index} has an invalid scraped_at value: "
                f"{scraped_at}"
            ) from error

        # Every record must declare its document type.
        doc_type = metadata.get("doc_type")

        if not isinstance(doc_type, str) or not doc_type:
            raise ValueError(
                f"Row {index} has no metadata.doc_type."
            )

        # Validate embeddings.
        if not isinstance(embedding, list):
            raise ValueError(
                f"Row {index} embedding is not a list."
            )

        if len(embedding) != EMBEDDING_DIMENSIONS:
            raise ValueError(
                f"Row {index} embedding has "
                f"{len(embedding)} dimensions instead of "
                f"{EMBEDDING_DIMENSIONS}."
            )

        if not all(
            isinstance(value, (int, float))
            for value in embedding
        ):
            raise ValueError(
                f"Row {index} embedding contains "
                "a non-numeric value."
            )

        # Detect duplicate upsert keys.
        unique_key = (
            source_url,
            chunk_index,
        )

        if unique_key in seen_keys:
            raise ValueError(
                "Duplicate (source_url, chunk_index) found: "
                f"{unique_key}"
            )

        seen_keys.add(unique_key)
        counts[doc_type] += 1

    # Validate the dataset composition.
    validate_dataset_counts(
        total_rows=len(rows),
        counts=counts,
        allow_supplemental_programs=allow_supplemental_programs,
        expected_supplemental_rows=expected_supplemental_rows,
    )

    print("\nValidation passed", flush=True)

    print(
        f"Total rows: {len(rows):,}",
        flush=True,
    )

    for doc_type, count in sorted(counts.items()):
        print(
            f"{doc_type}: {count:,}",
            flush=True,
        )

    return rows

# ==========================================================
# Dataset Validation
# ==========================================================
# Determines whether the JSON file is:
#
#   • Catalog dataset
#   • CV dataset
#
# Any other document composition is rejected.
def validate_dataset_counts(
    total_rows: int,
    counts: Counter[str],
    *,
    allow_supplemental_programs: bool = False,
    expected_supplemental_rows: int | None = None,
) -> None:
    """Validate catalog, CV, or an approved supplemental delivery."""

    actual_counts = dict(counts)
    doc_types = set(actual_counts)

    if allow_supplemental_programs:
        if expected_supplemental_rows is None:
            raise ValueError(
                "A supplemental delivery needs an expected row count "
                "(pass --expect N)."
            )

        expected = {
            SUPPLEMENTAL_PROGRAM_DOC_TYPE: expected_supplemental_rows
        }

        if (
            doc_types != {SUPPLEMENTAL_PROGRAM_DOC_TYPE}
            or total_rows != expected_supplemental_rows
            or actual_counts != expected
        ):
            raise ValueError(
                "The supplemental program counts do not match "
                "the expected delivery.\n"
                f"Expected: {expected}\n"
                f"Found: {actual_counts}"
            )

        return

    catalog_doc_types = set(
        CATALOG_EXPECTED_COUNTS
    )

    if doc_types == catalog_doc_types:
        if actual_counts != CATALOG_EXPECTED_COUNTS:
            raise ValueError(
                "The catalog counts do not match the "
                "expected delivery.\n"
                f"Expected: {CATALOG_EXPECTED_COUNTS}\n"
                f"Found: {actual_counts}"
            )

        expected_total = sum(
            CATALOG_EXPECTED_COUNTS.values()
        )

        if total_rows != expected_total:
            raise ValueError(
                f"Expected {expected_total:,} catalog rows, "
                f"but found {total_rows:,}."
            )

        return

    if doc_types == {"cv"}:
        if total_rows != actual_counts["cv"]:
            raise ValueError(
                "The CV row count does not match "
                "the doc_type count."
            )

        return

    raise ValueError(
        "Unexpected dataset composition.\n"
        "Expected either:\n"
        f"- Catalog: {CATALOG_EXPECTED_COUNTS}\n"
        "- CV: {'cv': number of CV rows}\n"
        f"Found: {actual_counts}"
    )

# ==========================================================
# Row Transformation
# ==========================================================
# Converts one JSON object into the format expected by the
# knowledge_entry database table.
def prepare_row(
    row: dict[str, Any],
) -> dict[str, Any]:
    """Convert one JSON row into database-ready values."""

    return {
        "source_url": row["source_url"],
        "chunk_index": row["chunk_index"],
        "chunk_text": row["chunk_text"],
        "facts": row["facts"],
        "metadata": row["metadata"],
        "content_hash": row["content_hash"],
        "scraped_at": parse_datetime(
            row["scraped_at"]
        ),
        "embedding": row["embedding"],
    }


# ==========================================================
# Database UPSERT
# ==========================================================
# Inserts new rows into Neon.
#
# If a row already exists, PostgreSQL updates only the
# content-related fields whose content hash changed.
#
# This prevents duplicates while keeping the database current.
def upsert_batch(
    session: Session,
    batch: list[dict[str, Any]],
) -> None:
    """Insert or update one batch in knowledge_entry."""

    # Access the physical SQLAlchemy table.
    # This avoids conflicts with the reserved "metadata" name.
    table = KnowledgeEntry.__table__

    # Build an INSERT statement.
    statement = insert(table).values(batch)

    # Reference incoming values.
    excluded = statement.excluded

    # Compare hashes to determine whether content changed.
    content_changed = table.c.content_hash.is_distinct_from(
        excluded.content_hash
    )

    # Perform an UPSERT using the repository key:
    # (source_url, chunk_index)
    statement = statement.on_conflict_do_update(
        index_elements=[
            table.c.source_url,
            table.c.chunk_index,
        ],
        set_={
            "scraped_at": excluded.scraped_at,

            "chunk_text": case(
                (
                    content_changed,
                    excluded.chunk_text,
                ),
                else_=table.c.chunk_text,
            ),

            "facts": case(
                (
                    content_changed,
                    excluded.facts,
                ),
                else_=table.c.facts,
            ),

            "metadata": case(
                (
                    content_changed,
                    excluded.metadata,
                ),
                else_=table.c.metadata,
            ),

            "embedding": case(
                (
                    content_changed,
                    excluded.embedding,
                ),
                else_=table.c.embedding,
            ),

            "content_hash": case(
                (
                    content_changed,
                    excluded.content_hash,
                ),
                else_=table.c.content_hash,
            ),

            "updated_at": case(
                (
                    content_changed,
                    func.now(),
                ),
                else_=table.c.updated_at,
            ),
        },
    )

    # Execute the UPSERT statement.
    session.execute(statement)

# ==========================================================
# Batch Database Loader
# ==========================================================
# Loads validated rows into Neon in configurable batches.
#
# Why batches are used:
#   • Prevents one enormous database transaction
#   • Reduces memory and connection pressure
#   • Makes progress visible in the terminal
#   • Allows a failed batch to roll back safely
def load_into_neon(
    rows: list[dict[str, Any]],
    batch_size: int,
    limit: int | None = None,
) -> None:
    """Load validated rows into Neon in batches."""

    # Batch size must be a positive number.
    if batch_size <= 0:
        raise ValueError(
            "batch_size must be greater than zero."
        )

    # Optional test limit must also be positive.
    if limit is not None and limit <= 0:
        raise ValueError(
            "limit must be greater than zero."
        )

    # If a limit was provided, load only that many rows.
    # This is useful for safe testing before a full import.
    selected_rows = (
        rows[:limit]
        if limit is not None
        else rows
    )

    total = len(selected_rows)

    print(
        f"\nPreparing to load {total:,} rows "
        "into Neon...",
        flush=True,
    )

    # Open one SQLAlchemy session for the import process.
    with SessionLocal() as session:
        try:
            # Process rows in fixed-size batches.
            for start in range(
                0,
                total,
                batch_size,
            ):
                # Select the current raw JSON batch.
                raw_batch = selected_rows[
                    start : start + batch_size
                ]

                # Convert raw JSON rows into database-ready values.
                batch = [
                    prepare_row(row)
                    for row in raw_batch
                ]

                # Insert new rows or update changed rows.
                upsert_batch(
                    session=session,
                    batch=batch,
                )

                # Commit only after the current batch succeeds.
                session.commit()

                completed = min(
                    start + batch_size,
                    total,
                )

                # Display progress in the terminal.
                print(
                    f"Loaded {completed:,}/{total:,} rows",
                    flush=True,
                )

        except Exception:
            # Roll back the active batch if anything fails.
            session.rollback()

            print(
                "\nLoad failed. "
                "The current batch was rolled back.",
                flush=True,
            )

            # Re-raise the original error so the traceback is visible.
            raise

    print(
        "\nDataset load completed successfully.",
        flush=True,
    )

    # ==========================================================
# Command-Line Interface
# ==========================================================
# Handles terminal arguments and decides whether the script
# should only validate the dataset or also load it into Neon.
def main() -> None:
    """Run validation or load rows into Neon."""

    parser = argparse.ArgumentParser(
        description=(
            "Validate and load catalog, supplemental program, "
            "or CV rows into the Neon knowledge_entry table."
        )
    )

    parser.add_argument(
        "json_path",
        type=Path,
        help="Path to the JSON file.",
    )

    parser.add_argument(
        "--load",
        action="store_true",
        help=(
            "Write rows to Neon after validation. "
            "Without this option, the script only validates."
        ),
    )

    parser.add_argument(
        "--supplemental-programs",
        action="store_true",
        help=(
            "Accept a program_map-only delivery. Requires --expect."
        ),
    )

    parser.add_argument(
        "--expect",
        type=int,
        default=None,
        help=(
            "Number of rows a supplemental delivery should contain, "
            "e.g. --expect 19. Stating it catches a truncated or "
            "double-written file."
        ),
    )

    parser.add_argument(
        "--batch-size",
        type=int,
        default=100,
        help=(
            "Number of rows written in each database "
            "batch. Default: 100."
        ),
    )

    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help=(
            "Optional number of rows to load for "
            "a small database test."
        ),
    )

    args = parser.parse_args()

    if (
        args.supplemental_programs
        and args.limit is not None
    ):
        parser.error(
            "--limit cannot be used with "
            "--supplemental-programs."
        )

    if args.supplemental_programs and args.expect is None:
        parser.error(
            "--supplemental-programs requires --expect N "
            "(the number of rows the file should contain)."
        )

    if args.expect is not None and not args.supplemental_programs:
        parser.error(
            "--expect only applies to --supplemental-programs."
        )

    rows = load_rows(
        args.json_path,
        allow_supplemental_programs=(
            args.supplemental_programs
        ),
        expected_supplemental_rows=args.expect,
    )

    if not args.load:
        print(
            "\nValidation only. "
            "Neon was not modified.",
            flush=True,
        )
        return

    load_into_neon(
        rows=rows,
        batch_size=args.batch_size,
        limit=args.limit,
    )

# ==========================================================
# Script Entry Point
# ==========================================================
# Runs main() only when this file is executed directly.
if __name__ == "__main__":
    main()