import os
import sys
import time
from pathlib import Path
from dotenv import load_dotenv
import chromadb
from chromadb.utils import embedding_functions
from openai import OpenAI

# Resolve base directories dynamically
CURRENT_DIR = Path(__file__).resolve().parent
APPS_DATA_DIR = CURRENT_DIR.parent if CURRENT_DIR.name == "dallasai" else CURRENT_DIR
REPO_ROOT = APPS_DATA_DIR.parent.parent

# Inject apps/data/ into path
if str(APPS_DATA_DIR) not in sys.path:
    sys.path.insert(0, str(APPS_DATA_DIR))

# Load configurations
load_dotenv(str(REPO_ROOT / ".env"))
api_key = os.getenv("OPENROUTER_API_KEY")
db_path = os.getenv("CHROMA_DB_PATH", str(APPS_DATA_DIR / "chroma_db"))
collection_name = os.getenv("CHROMA_COLLECTION_NAME", "dallas_college_kb")

if not api_key:
    # Try alternative parent .env
    load_dotenv(str(REPO_ROOT.parent / ".env"))
    api_key = os.getenv("OPENROUTER_API_KEY")

def query_llm_fast(prompt: str) -> str:
    """
    Queries OpenRouter using a fast, free LLM model with fallback options.
    
    Concept:
    - Minimizes API failures by checking multiple models in sequence.
    - Uses a short (8s) timeout to prevent hanging on slow network requests.
    - Provides a mock response if no API key is set to allow local-only testing.
    """
    if not api_key:
        return "[LOCAL MOCK LLM] (No API key found in environment. Please set OPENROUTER_API_KEY in .env)"
        
    # Free models hosted on OpenRouter for evaluation/testing
    models = [
        "openrouter/free",
        "meta-llama/llama-3.2-3b-instruct:free",
        "meta-llama/llama-3.3-70b-instruct:free"
    ]
    
    # Initialize the OpenAI-compatible OpenRouter client
    client = OpenAI(
        base_url="https://openrouter.ai/api/v1",
        api_key=api_key,
        default_headers={
            "HTTP-Referer": "https://github.com/Dallas-College-AI-Club/success-coach-chatbot",
            "X-Title": "RAG HTML Interactive Visualizer",
        }
    )

    # Loop through each model until one responds successfully
    for model in models:
        try:
            print(f"  🤖 Querying LLM via '{model}'...")
            start_time = time.time()
            completion = client.chat.completions.create(
                model=model,
                messages=[
                    {
                        "role": "system",
                        "content": (
                            "You are an Academic Success Coach for Dallas College. "
                            "Answer the student's question using ONLY the provided context. "
                            "If the context does not contain the answer, politely state that you don't know. "
                            "Keep your response concise (2-4 sentences max)."
                        )
                    },
                    {"role": "user", "content": prompt}
                ],
                timeout=8  # Enforces rapid response, bypassing slow gateways
            )
            elapsed = time.time() - start_time
            print(f"  ⏱️ LLM response received in {elapsed:.2f} seconds.")
            return completion.choices[0].message.content.strip()
        except Exception as e:
            print(f"  ⚠️  Model '{model}' failed or timed out: {e}. Trying next fallback...")
            
    return "❌ LLM Query failed: All models timed out or failed to respond."

def main():
    """
    Main REPL loop for interactive RAG evaluation.
    
    Steps:
    1. Connects to the local persistent ChromaDB instance generated by pipeline_runner.py.
    2. Loads the target collection containing the scraped, converted, and chunked HTML syllabi.
    3. Prompts the user for a query, searches the database, and converts distance metrics to similarity scores.
    4. Formats and prints matching documents and meta fields.
    5. Optionally triggers OpenRouter LLM generation based on the retrieved context.
    """
    print("=" * 70)
    print("  DALLAS COLLEGE RAG INTERACTIVE VISUALIZER (REAL HTML SYLLABI)")
    print("=" * 70)
    
    print(f"📦 Connecting to ChromaDB at: {db_path}")
    db_client = chromadb.PersistentClient(path=db_path)
    
    # ChromaDB's default embedding function (all-MiniLM-L6-v2)
    embedding_fn = embedding_functions.DefaultEmbeddingFunction()
    
    try:
        # Load the collection created by the pipeline runner
        collection = db_client.get_collection(
            name=collection_name,
            embedding_function=embedding_fn
        )
        count = collection.count()
        print(f"✅ Connected! Collection '{collection_name}' contains {count} chunks.")
    except Exception as e:
        print(f"❌ Error: Collection '{collection_name}' could not be loaded: {str(e)}")
        print("💡 Please run the ingestion pipeline runner first to index your HTML files:")
        print("   /venv/bin/python dallasai/pipeline_runner.py")
        sys.exit(1)

    # Begin the command line interface loop
    while True:
        print("\n" + "=" * 60)
        query = input("🔍 Enter student query (or type 'exit' / 'q' to quit): ").strip()
        if not query or query.lower() in ['exit', 'q']:
            print("Goodbye!")
            break
            
        start_retrieval = time.time()
        # Query ChromaDB collection for top 3 matching chunks
        res = collection.query(
            query_texts=[query],
            n_results=3
        )
        elapsed_retrieval = time.time() - start_retrieval
        print(f"\n🔎 Searching ChromaDB (n_results=3)... [Took {elapsed_retrieval:.4f}s]")
        
        retrieved_docs = res["documents"][0]
        retrieved_meta = res["metadatas"][0]
        distances = res["distances"][0]
        
        print("\n💡 RETRIEVED CHUNKS:")
        context_parts = []
        for i in range(len(retrieved_docs)):
            # Distance ranges from 0 (identical) to 2 (dissimilar). We convert to similarity:
            score = 1.0 - distances[i]
            meta = retrieved_meta[i]
            doc = retrieved_docs[i]
            print("-" * 60)
            print(f"[{i+1}] COURSE: {meta.get('course_id', 'UNKNOWN')} | SECTION: {meta.get('header_path', 'Root')} (Similarity Score: {score:.4f})")
            print(f"File: {meta.get('source_file')} | Doc Type: {meta.get('document_type')}")
            print(f"Content:\n{doc}")
            context_parts.append(f"Source: {meta.get('course_id')} ({meta.get('header_path')})\nContent:\n{doc}")
            
        print("-" * 60)
        
        # Format context and prompt payload
        context_str = "\n\n".join(context_parts)
        rag_prompt = (
            f"Context from course syllabi:\n{context_str}\n\n"
            f"Question: {query}\n"
        )
        
        # User input option to run the LLM generator or just print the prompt
        run_llm = input("\n🤖 Run LLM generation over this context? (y/n): ").strip().lower()
        if run_llm == 'y':
            start_llm = time.time()
            answer = query_llm_fast(rag_prompt)
            elapsed_llm = time.time() - start_llm
            print(f"\n💬 LLM ANSWER:\n{answer}\n")
            print(f"⏱️  Performance Metrics:")
            print(f"   - Vector Search: {elapsed_retrieval:.4f}s")
            print(f"   - LLM Generation: {elapsed_llm:.2f}s")
            print(f"   - Total Processing: {elapsed_retrieval + elapsed_llm:.2f}s")
        else:
            print("\nSkipping LLM. Prompt that would be sent:")
            print("=" * 50)
            print(rag_prompt)
            print("=" * 50)

if __name__ == "__main__":
    main()
