"""Directory sync: Airtable base -> Module 4 tables (Issue #43/#44/#45).

Airtable is the AUTHORING surface (forms, verification workflow, governed
vocabularies); Postgres remains the serving store the bot queries. This sync
is one-way (Airtable -> Postgres), idempotent, and keyed on Airtable record
ids stored in the external_id columns:

- contacts, academic_units, assignments: upsert by external_id. On first sync,
  rows that pre-exist from seeds (no matching external_id) are ADOPTED by
  exact name match and their external_id set to the Airtable record id — so
  seeded units like "ETMS" or "General / All" never duplicate.
- resource_categories, help_topics: governed vocabularies — INSERT missing
  names only, never overwrite existing rows (the DB owns wording like the
  routing_model boundary text).
- assignment_topics: rebuilt per synced assignment from the Help Topics links.
- student_guidance: one row per resource category, updated in place.
- ALIASES ARE NOT SYNCED: the vocabulary lives ONLY in Postgres
  (db/seed_aliases.sql, versioned in git; growth via unresolved_phrases ->
  reviewed additions to that file). Airtable stays the surface for
  staff-collected data only.

Directory data is staff-entered public information (team decision 2026-07-07)
— this is NOT pipeline/raw_documents data; raw stays scraper-only.

Settings (.env): AIRTABLE_TOKEN (personal access token with data.records:read
on the base), AIRTABLE_BASE_ID (e.g. appBGNem98aDRFiAy).

CLI:
    python -m pipeline.load_directory              # sync everything
    python -m pipeline.load_directory --dry-run    # fetch + report, no writes
"""

from __future__ import annotations

import argparse
import os
import sys
from typing import Any, Iterator, Optional

API_BASE = "https://api.airtable.com/v0"

# Airtable table + field names as generated by the base builder — adjust here
# if the base is renamed (names, not ids, keep this readable for the team).
T_CONTACTS = "Contacts"
T_UNITS = "Academic Units"
T_CATEGORIES = "Resource Categories"
T_TOPICS = "Help Topics"
T_ASSIGNMENTS = "Assignments"
T_GUIDANCE = "Student Guidance"

F = {
    "contact_name": "Name",
    "contact_email": "Email",
    "contact_helps": "Helps With",
    "contact_active": "Active",
    "contact_verified": "Last Verified Date",
    "unit_name": "Name",
    "category_name": "Name",
    "category_routing": "Routing Model",
    "topic_name": "Name",
    "asg_contact": "Contact",
    "asg_unit": "Academic Unit",
    "asg_category": "Resource Category",
    "asg_program": "Degree or Program",
    "asg_scope": "Applies to",
    "cat_description": "Description",
    "cat_clarify": "Clarify Label",
    "topic_prompt": "Disambiguation Prompt",
    "topic_cats": "Categories",
    "asg_criteria": "Eligibility Criteria",
    "asg_topics": "Help Topics",
    "guid_category": "Resource Category",
    "guid_prep": "Prep Steps",
    "guid_awareness": "Awareness Message",
}


def fetch_records(table: str, token: str, base_id: str) -> list[dict]:
    """All records of a table (handles pagination)."""
    import requests  # lazy

    records: list[dict] = []
    params: dict[str, Any] = {"pageSize": 100}
    url = f"{API_BASE}/{base_id}/{requests.utils.quote(table)}"
    while True:
        resp = requests.get(url, params=params,
                            headers={"Authorization": f"Bearer {token}"}, timeout=60)
        resp.raise_for_status()
        payload = resp.json()
        records.extend(payload.get("records", []))
        offset = payload.get("offset")
        if not offset:
            return records
        params["offset"] = offset


def first_link(value) -> Optional[str]:
    """Airtable linked fields return lists of record ids; take the single link."""
    if isinstance(value, list) and value:
        return value[0]
    return None


def one_link(fields: dict, field: str, rec_id: str) -> Optional[str]:
    """first_link + LINT when extra links are being dropped — contradictions
    are reported, never silently interpreted."""
    value = fields.get(field)
    if isinstance(value, list) and len(value) > 1:
        print(f"  LINT {rec_id}: field {field!r} has {len(value)} links; "
              f"using the first — fix in Airtable", file=sys.stderr)
    return first_link(value)


# ---------------------------------------------------------------------------
# Upsert helpers (adopt-by-name so seeded rows never duplicate)
# ---------------------------------------------------------------------------

def upsert_by_external_id(cur, table: str, external_id: str, name: str,
                          set_cols: dict) -> int:
    """Generic upsert: match external_id; else adopt an existing row by exact
    name (setting its external_id); else insert. Returns the row id."""
    cur.execute(f"SELECT id FROM {table} WHERE external_id = %s", (external_id,))
    row = cur.fetchone()
    if row is None:
        cur.execute(
            f"SELECT id FROM {table} WHERE external_id IS NULL AND name = %s LIMIT 1",
            (name,))
        row = cur.fetchone()
        if row:
            cur.execute(f"UPDATE {table} SET external_id = %s WHERE id = %s",
                        (external_id, row[0]))
    if row:
        row_id = row[0]
        assignments = ", ".join(f"{c} = %s" for c in set_cols)
        cur.execute(
            f"""UPDATE {table} SET {assignments}
                WHERE id = %s AND ({", ".join(set_cols)}) IS DISTINCT FROM
                      ({", ".join("%s" for _ in set_cols)})""",
            (*set_cols.values(), row_id, *set_cols.values()))
        return row_id
    cols = ["external_id", *set_cols.keys()]
    cur.execute(
        f"""INSERT INTO {table} ({", ".join(cols)})
            VALUES ({", ".join("%s" for _ in cols)}) RETURNING id""",
        (external_id, *set_cols.values()))
    return cur.fetchone()[0]


def ensure_vocab(cur, table: str, name: str) -> int:
    """Governed vocabulary: insert if missing, never overwrite existing."""
    cur.execute(f"SELECT id FROM {table} WHERE name = %s", (name,))
    row = cur.fetchone()
    if row:
        return row[0]
    if table == "resource_categories":
        cur.execute(
            "INSERT INTO resource_categories (name) VALUES (%s) RETURNING id", (name,))
    else:
        cur.execute(f"INSERT INTO {table} (name) VALUES (%s) RETURNING id", (name,))
    return cur.fetchone()[0]


# ---------------------------------------------------------------------------
# The sync
# ---------------------------------------------------------------------------

def sync(conn, token: str, base_id: str, dry_run: bool = False) -> dict[str, int]:
    tables = {
        "units": fetch_records(T_UNITS, token, base_id),
        "categories": fetch_records(T_CATEGORIES, token, base_id),
        "topics": fetch_records(T_TOPICS, token, base_id),
        "contacts": fetch_records(T_CONTACTS, token, base_id),
        "assignments": fetch_records(T_ASSIGNMENTS, token, base_id),
        "guidance": fetch_records(T_GUIDANCE, token, base_id),
    }
    counts = {k: len(v) for k, v in tables.items()}
    if dry_run:
        return counts

    with conn.cursor() as cur:
        # institution anchor for academic_units (single-institution reality)
        cur.execute("SELECT id FROM institutions WHERE name = 'Dallas College'")
        row = cur.fetchone()
        if row is None:
            cur.execute(
                """INSERT INTO institutions (external_id, name, website)
                   VALUES ('inst-dallas-college', 'Dallas College',
                           'https://www.dallascollege.edu') RETURNING id""")
            row = cur.fetchone()
        institution_id = row[0]

        unit_ids: dict[str, int] = {}     # airtable record id -> pg id
        for r in tables["units"]:
            name = (r["fields"].get(F["unit_name"]) or "").strip()
            if not name:
                continue
            cur.execute("SELECT id FROM academic_units WHERE external_id = %s", (r["id"],))
            hit = cur.fetchone()
            if hit:
                # renames must propagate: canonical resolve + alias seeds key on name
                cur.execute(
                    """UPDATE academic_units SET name = %s
                       WHERE id = %s AND name IS DISTINCT FROM %s""",
                    (name, hit[0], name))
            if hit is None:
                cur.execute(
                    """SELECT id FROM academic_units WHERE name = %s
                       AND (external_id IS NULL OR external_id LIKE 'unit-%%') LIMIT 1""",
                    (name,))
                hit = cur.fetchone()
                if hit:  # adopt the seeded row; Airtable id becomes canonical
                    cur.execute("UPDATE academic_units SET external_id = %s WHERE id = %s",
                                (r["id"], hit[0]))
            if hit:
                unit_ids[r["id"]] = hit[0]
            else:
                cur.execute(
                    """INSERT INTO academic_units (external_id, institution_id, name)
                       VALUES (%s, %s, %s) RETURNING id""",
                    (r["id"], institution_id, name))
                unit_ids[r["id"]] = cur.fetchone()[0]

        category_ids = {}
        for r in tables["categories"]:
            name = (r["fields"].get(F["category_name"]) or "").strip()
            if not name:
                continue
            cid = ensure_vocab(cur, "resource_categories", name)
            category_ids[r["id"]] = cid
            desc = r["fields"].get(F["cat_description"]) or None
            clarify = r["fields"].get(F["cat_clarify"]) or None
            if desc or clarify:
                cur.execute(
                    """UPDATE resource_categories
                       SET description = COALESCE(%s, description),
                           clarify_label = COALESCE(%s, clarify_label)
                       WHERE id = %s AND (description, clarify_label)
                             IS DISTINCT FROM (COALESCE(%s, description),
                                               COALESCE(%s, clarify_label))""",
                    (desc, clarify, cid, desc, clarify))
        topic_ids = {}
        for r in tables["topics"]:
            name = (r["fields"].get(F["topic_name"]) or "").strip()
            if not name:
                continue
            tid = ensure_vocab(cur, "help_topics", name)
            topic_ids[r["id"]] = tid
            prompt = r["fields"].get(F["topic_prompt"]) or None
            if prompt:
                cur.execute(
                    """UPDATE help_topics SET disambiguation_prompt = %s
                       WHERE id = %s AND disambiguation_prompt IS DISTINCT FROM %s""",
                    (prompt, tid, prompt))
            cat_links = [category_ids.get(x) for x in (r["fields"].get(F["topic_cats"]) or [])]
            cat_links = [c for c in cat_links if c]
            if cat_links:
                cur.execute("DELETE FROM topic_categories WHERE help_topic_id = %s", (tid,))
                for c in cat_links:
                    cur.execute(
                        """INSERT INTO topic_categories
                               (help_topic_id, resource_category_id, is_default)
                           VALUES (%s, %s, %s) ON CONFLICT DO NOTHING""",
                        (tid, c, len(cat_links) == 1))
        # reconcile defaults across ALL writers (seed rows survive topics with
        # no Airtable links): default <=> the topic routes to exactly one category
        cur.execute(
            """UPDATE topic_categories tc SET is_default = (x.cnt = 1)
               FROM (SELECT help_topic_id, count(*) AS cnt
                     FROM topic_categories GROUP BY help_topic_id) x
               WHERE x.help_topic_id = tc.help_topic_id
                 AND tc.is_default IS DISTINCT FROM (x.cnt = 1)""")

        contact_ids: dict[str, int] = {}
        for r in tables["contacts"]:
            f = r["fields"]
            name = (f.get(F["contact_name"]) or "").strip()
            if not name:
                continue
            contact_ids[r["id"]] = upsert_by_external_id(
                cur, "contacts", r["id"], name,
                {"name": name,
                 "email": f.get(F["contact_email"]) or None,
                 "helps_with": f.get(F["contact_helps"]) or None,
                 "active": bool(f.get(F["contact_active"], False)),
                 "last_verified_date": f.get(F["contact_verified"]) or None})

        for r in tables["assignments"]:
            f = r["fields"]
            contact = contact_ids.get(one_link(f, F["asg_contact"], r["id"]))
            unit = unit_ids.get(one_link(f, F["asg_unit"], r["id"]))
            category = category_ids.get(one_link(f, F["asg_category"], r["id"]))
            if not (contact and category):
                print(f"  assignment {r['id']}: missing contact/category link; skipped",
                      file=sys.stderr)
                continue
            # explicit scope: default unit-wide; program text only when specific.
            # Sync-time LINT: contradictions are reported and normalized, never
            # silently interpreted (the DB CHECK would reject them anyway).
            scope = (f.get(F["asg_scope"]) or "").strip()
            if scope not in ("", "Whole school/unit", "Specific program(s) only"):
                print(f"  LINT assignment {r['id']}: unknown 'Applies to' value "
                      f"{scope!r} — row skipped; fix the select option in Airtable",
                      file=sys.stderr)
                continue
            unit_wide = scope != "Specific program(s) only"
            program = f.get(F["asg_program"]) or None
            if unit_wide and program:
                print(f"  LINT assignment {r['id']}: scope says whole-unit but a "
                      f"program is set ({program!r}) — ignoring the program; fix in Airtable",
                      file=sys.stderr)
                program = None
            if not unit_wide and not program:
                print(f"  LINT assignment {r['id']}: scope says program-specific but "
                      f"no program is set — treating as unit-wide; fix in Airtable",
                      file=sys.stderr)
                unit_wide = True
            cur.execute("SELECT id FROM assignments WHERE external_id = %s", (r["id"],))
            hit = cur.fetchone()
            if hit and unit_wide:
                # a scope flip to whole-unit must also clear the integer program
                # ref, or the two-sided CHECK rejects the update
                cur.execute(
                    """UPDATE assignments SET degree_plan_id = NULL
                       WHERE id = %s AND degree_plan_id IS NOT NULL""",
                    (hit[0],))
            values = (contact, unit, category, unit_wide, program,
                      f.get(F["asg_criteria"]) or None)
            if hit:
                cur.execute(
                    """UPDATE assignments SET contact_id=%s, academic_unit_id=%s,
                           resource_category_id=%s, applies_to_all_programs=%s,
                           degree_or_program=%s, criteria=%s
                       WHERE id = %s AND (contact_id, academic_unit_id,
                             resource_category_id, applies_to_all_programs,
                             degree_or_program, criteria)
                             IS DISTINCT FROM (%s, %s, %s, %s, %s, %s)""",
                    (*values, hit[0], *values))
                assignment_id = hit[0]
            else:
                cur.execute(
                    """INSERT INTO assignments (external_id, contact_id,
                           academic_unit_id, resource_category_id,
                           applies_to_all_programs, degree_or_program, criteria)
                       VALUES (%s, %s, %s, %s, %s, %s, %s) RETURNING id""",
                    (r["id"], *values))
                assignment_id = cur.fetchone()[0]
            # rebuild topic links for this assignment
            cur.execute("DELETE FROM assignment_topics WHERE assignment_id = %s",
                        (assignment_id,))
            for topic_rec in (f.get(F["asg_topics"]) or []):
                topic_id = topic_ids.get(topic_rec)
                if topic_id:
                    cur.execute(
                        """INSERT INTO assignment_topics (assignment_id, help_topic_id)
                           VALUES (%s, %s) ON CONFLICT DO NOTHING""",
                        (assignment_id, topic_id))

        seen_guidance: set[int] = set()
        for r in tables["guidance"]:
            f = r["fields"]
            category = category_ids.get(one_link(f, F["guid_category"], r["id"]))
            if not category:
                continue
            if category in seen_guidance:
                print(f"  LINT guidance {r['id']}: duplicate row for this category "
                      f"— keeping the first, skipping this one; fix in Airtable",
                      file=sys.stderr)
                continue
            seen_guidance.add(category)
            prep = f.get(F["guid_prep"]) or None
            awareness = f.get(F["guid_awareness"]) or None
            cur.execute("SELECT id FROM student_guidance WHERE resource_category_id = %s",
                        (category,))
            hit = cur.fetchone()
            if hit:
                cur.execute(
                    """UPDATE student_guidance SET prep_steps=%s, awareness_msg=%s
                       WHERE id=%s AND (prep_steps, awareness_msg)
                             IS DISTINCT FROM (%s, %s)""",
                    (prep, awareness, hit[0], prep, awareness))
            else:
                cur.execute(
                    """INSERT INTO student_guidance
                           (resource_category_id, prep_steps, awareness_msg)
                       VALUES (%s, %s, %s)""",
                    (category, prep, awareness))
    conn.commit()
    return counts


def main(argv: Optional[list[str]] = None) -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dry-run", action="store_true",
                    help="fetch and report record counts; write nothing")
    args = ap.parse_args(argv)

    from dotenv import load_dotenv
    load_dotenv()
    token = os.environ.get("AIRTABLE_TOKEN", "").strip()
    base_id = os.environ.get("AIRTABLE_BASE_ID", "").strip()
    if not token or not base_id:
        raise SystemExit("Set AIRTABLE_TOKEN and AIRTABLE_BASE_ID in .env "
                         "(see .env.example).")

    from db.client import get_connection  # the one-file adapter (ADR-008)

    with get_connection() as conn:
        counts = sync(conn, token, base_id, dry_run=args.dry_run)
    label = "fetched (dry run)" if args.dry_run else "synced"
    print(f"directory {label}: " + ", ".join(f"{k}={v}" for k, v in counts.items()))


if __name__ == "__main__":
    main()
