"""Directory sync: Airtable base -> Module 4 tables (Issue #43/#44/#45).

Airtable is the AUTHORING surface (forms, verification workflow, governed
vocabularies); Postgres remains the serving store the bot queries. This sync
is one-way (Airtable -> Postgres), idempotent, and keyed on Airtable record
ids stored in the external_id columns:

- contacts, academic_units, assignments: upsert by external_id. On first sync,
  rows that pre-exist from seeds (no matching external_id) are ADOPTED by
  exact name match and their external_id set to the Airtable record id — so
  seeded units like "ETMS" or "General / All" never duplicate.
- resource_categories, help_topics: governed vocabularies — INSERT missing
  names only, never overwrite existing rows (the DB owns wording like the
  routing_model boundary text).
- assignment_topics: rebuilt per synced assignment from the Help Topics links.
- student_guidance: one row per resource category, updated in place.

Directory data is staff-entered public information (team decision 2026-07-07)
— this is NOT pipeline/raw_documents data; raw stays scraper-only.

Settings (.env): AIRTABLE_TOKEN (personal access token with data.records:read
on the base), AIRTABLE_BASE_ID (e.g. appBGNem98aDRFiAy).

CLI:
    python -m pipeline.load_directory              # sync everything
    python -m pipeline.load_directory --dry-run    # fetch + report, no writes
"""

from __future__ import annotations

import argparse
import os
import sys
from typing import Any, Iterator, Optional

API_BASE = "https://api.airtable.com/v0"

# Airtable table + field names as generated by the base builder — adjust here
# if the base is renamed (names, not ids, keep this readable for the team).
T_CONTACTS = "Contacts"
T_UNITS = "Academic Units"
T_CATEGORIES = "Resource Categories"
T_TOPICS = "Help Topics"
T_ASSIGNMENTS = "Assignments"
T_GUIDANCE = "Student Guidance"

F = {
    "contact_name": "Name",
    "contact_email": "Email",
    "contact_helps": "Helps With",
    "contact_active": "Active",
    "contact_verified": "Last Verified Date",
    "unit_name": "Name",
    "category_name": "Name",
    "category_routing": "Routing Model",
    "topic_name": "Name",
    "asg_contact": "Contact",
    "asg_unit": "Academic Unit",
    "asg_category": "Resource Category",
    "asg_program": "Degree or Program",
    "asg_criteria": "Eligibility Criteria",
    "asg_topics": "Help Topics",
    "guid_category": "Resource Category",
    "guid_prep": "Prep Steps",
    "guid_awareness": "Awareness Message",
}


def fetch_records(table: str, token: str, base_id: str) -> list[dict]:
    """All records of a table (handles pagination)."""
    import requests  # lazy

    records: list[dict] = []
    params: dict[str, Any] = {"pageSize": 100}
    url = f"{API_BASE}/{base_id}/{requests.utils.quote(table)}"
    while True:
        resp = requests.get(url, params=params,
                            headers={"Authorization": f"Bearer {token}"}, timeout=60)
        resp.raise_for_status()
        payload = resp.json()
        records.extend(payload.get("records", []))
        offset = payload.get("offset")
        if not offset:
            return records
        params["offset"] = offset


def first_link(value) -> Optional[str]:
    """Airtable linked fields return lists of record ids; take the single link."""
    if isinstance(value, list) and value:
        return value[0]
    return None


# ---------------------------------------------------------------------------
# Upsert helpers (adopt-by-name so seeded rows never duplicate)
# ---------------------------------------------------------------------------

def upsert_by_external_id(cur, table: str, external_id: str, name: str,
                          set_cols: dict) -> int:
    """Generic upsert: match external_id; else adopt an existing row by exact
    name (setting its external_id); else insert. Returns the row id."""
    cur.execute(f"SELECT id FROM {table} WHERE external_id = %s", (external_id,))
    row = cur.fetchone()
    if row is None:
        cur.execute(
            f"SELECT id FROM {table} WHERE external_id IS NULL AND name = %s LIMIT 1",
            (name,))
        row = cur.fetchone()
        if row:
            cur.execute(f"UPDATE {table} SET external_id = %s WHERE id = %s",
                        (external_id, row[0]))
    if row:
        row_id = row[0]
        assignments = ", ".join(f"{c} = %s" for c in set_cols)
        cur.execute(
            f"""UPDATE {table} SET {assignments}
                WHERE id = %s AND ({", ".join(set_cols)}) IS DISTINCT FROM
                      ({", ".join("%s" for _ in set_cols)})""",
            (*set_cols.values(), row_id, *set_cols.values()))
        return row_id
    cols = ["external_id", *set_cols.keys()]
    cur.execute(
        f"""INSERT INTO {table} ({", ".join(cols)})
            VALUES ({", ".join("%s" for _ in cols)}) RETURNING id""",
        (external_id, *set_cols.values()))
    return cur.fetchone()[0]


def ensure_vocab(cur, table: str, name: str) -> int:
    """Governed vocabulary: insert if missing, never overwrite existing."""
    cur.execute(f"SELECT id FROM {table} WHERE name = %s", (name,))
    row = cur.fetchone()
    if row:
        return row[0]
    if table == "resource_categories":
        cur.execute(
            "INSERT INTO resource_categories (name) VALUES (%s) RETURNING id", (name,))
    else:
        cur.execute(f"INSERT INTO {table} (name) VALUES (%s) RETURNING id", (name,))
    return cur.fetchone()[0]


# ---------------------------------------------------------------------------
# The sync
# ---------------------------------------------------------------------------

def sync(conn, token: str, base_id: str, dry_run: bool = False) -> dict[str, int]:
    tables = {
        "units": fetch_records(T_UNITS, token, base_id),
        "categories": fetch_records(T_CATEGORIES, token, base_id),
        "topics": fetch_records(T_TOPICS, token, base_id),
        "contacts": fetch_records(T_CONTACTS, token, base_id),
        "assignments": fetch_records(T_ASSIGNMENTS, token, base_id),
        "guidance": fetch_records(T_GUIDANCE, token, base_id),
    }
    counts = {k: len(v) for k, v in tables.items()}
    if dry_run:
        return counts

    with conn.cursor() as cur:
        # institution anchor for academic_units (single-institution reality)
        cur.execute("SELECT id FROM institutions WHERE name = 'Dallas College'")
        row = cur.fetchone()
        if row is None:
            cur.execute(
                """INSERT INTO institutions (external_id, name, website)
                   VALUES ('inst-dallas-college', 'Dallas College',
                           'https://www.dallascollege.edu') RETURNING id""")
            row = cur.fetchone()
        institution_id = row[0]

        unit_ids: dict[str, int] = {}     # airtable record id -> pg id
        for r in tables["units"]:
            name = (r["fields"].get(F["unit_name"]) or "").strip()
            if not name:
                continue
            cur.execute("SELECT id FROM academic_units WHERE external_id = %s", (r["id"],))
            hit = cur.fetchone()
            if hit is None:
                cur.execute(
                    """SELECT id FROM academic_units WHERE name = %s
                       AND (external_id IS NULL OR external_id LIKE 'unit-%%') LIMIT 1""",
                    (name,))
                hit = cur.fetchone()
                if hit:  # adopt the seeded row; Airtable id becomes canonical
                    cur.execute("UPDATE academic_units SET external_id = %s WHERE id = %s",
                                (r["id"], hit[0]))
            if hit:
                unit_ids[r["id"]] = hit[0]
            else:
                cur.execute(
                    """INSERT INTO academic_units (external_id, institution_id, name)
                       VALUES (%s, %s, %s) RETURNING id""",
                    (r["id"], institution_id, name))
                unit_ids[r["id"]] = cur.fetchone()[0]

        category_ids = {r["id"]: ensure_vocab(cur, "resource_categories",
                                              (r["fields"].get(F["category_name"]) or "").strip())
                        for r in tables["categories"]
                        if (r["fields"].get(F["category_name"]) or "").strip()}
        topic_ids = {r["id"]: ensure_vocab(cur, "help_topics",
                                           (r["fields"].get(F["topic_name"]) or "").strip())
                     for r in tables["topics"]
                     if (r["fields"].get(F["topic_name"]) or "").strip()}

        contact_ids: dict[str, int] = {}
        for r in tables["contacts"]:
            f = r["fields"]
            name = (f.get(F["contact_name"]) or "").strip()
            if not name:
                continue
            contact_ids[r["id"]] = upsert_by_external_id(
                cur, "contacts", r["id"], name,
                {"name": name,
                 "email": f.get(F["contact_email"]) or None,
                 "helps_with": f.get(F["contact_helps"]) or None,
                 "active": bool(f.get(F["contact_active"], False)),
                 "last_verified_date": f.get(F["contact_verified"]) or None})

        for r in tables["assignments"]:
            f = r["fields"]
            contact = contact_ids.get(first_link(f.get(F["asg_contact"])))
            unit = unit_ids.get(first_link(f.get(F["asg_unit"])))
            category = category_ids.get(first_link(f.get(F["asg_category"])))
            if not (contact and category):
                print(f"  assignment {r['id']}: missing contact/category link; skipped",
                      file=sys.stderr)
                continue
            cur.execute("SELECT id FROM assignments WHERE external_id = %s", (r["id"],))
            hit = cur.fetchone()
            values = (contact, unit, category,
                      f.get(F["asg_program"]) or None, f.get(F["asg_criteria"]) or None)
            if hit:
                cur.execute(
                    """UPDATE assignments SET contact_id=%s, academic_unit_id=%s,
                           resource_category_id=%s, degree_or_program=%s, criteria=%s
                       WHERE id = %s AND (contact_id, academic_unit_id,
                             resource_category_id, degree_or_program, criteria)
                             IS DISTINCT FROM (%s, %s, %s, %s, %s)""",
                    (*values, hit[0], *values))
                assignment_id = hit[0]
            else:
                cur.execute(
                    """INSERT INTO assignments (external_id, contact_id,
                           academic_unit_id, resource_category_id,
                           degree_or_program, criteria)
                       VALUES (%s, %s, %s, %s, %s, %s) RETURNING id""",
                    (r["id"], *values))
                assignment_id = cur.fetchone()[0]
            # rebuild topic links for this assignment
            cur.execute("DELETE FROM assignment_topics WHERE assignment_id = %s",
                        (assignment_id,))
            for topic_rec in (f.get(F["asg_topics"]) or []):
                topic_id = topic_ids.get(topic_rec)
                if topic_id:
                    cur.execute(
                        """INSERT INTO assignment_topics (assignment_id, help_topic_id)
                           VALUES (%s, %s) ON CONFLICT DO NOTHING""",
                        (assignment_id, topic_id))

        for r in tables["guidance"]:
            f = r["fields"]
            category = category_ids.get(first_link(f.get(F["guid_category"])))
            if not category:
                continue
            prep = f.get(F["guid_prep"]) or None
            awareness = f.get(F["guid_awareness"]) or None
            cur.execute("SELECT id FROM student_guidance WHERE resource_category_id = %s",
                        (category,))
            hit = cur.fetchone()
            if hit:
                cur.execute(
                    """UPDATE student_guidance SET prep_steps=%s, awareness_msg=%s
                       WHERE id=%s AND (prep_steps, awareness_msg)
                             IS DISTINCT FROM (%s, %s)""",
                    (prep, awareness, hit[0], prep, awareness))
            else:
                cur.execute(
                    """INSERT INTO student_guidance
                           (resource_category_id, prep_steps, awareness_msg)
                       VALUES (%s, %s, %s)""",
                    (category, prep, awareness))
    conn.commit()
    return counts


def main(argv: Optional[list[str]] = None) -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dry-run", action="store_true",
                    help="fetch and report record counts; write nothing")
    args = ap.parse_args(argv)

    from dotenv import load_dotenv
    load_dotenv()
    token = os.environ.get("AIRTABLE_TOKEN", "").strip()
    base_id = os.environ.get("AIRTABLE_BASE_ID", "").strip()
    if not token or not base_id:
        raise SystemExit("Set AIRTABLE_TOKEN and AIRTABLE_BASE_ID in .env "
                         "(see .env.example).")

    from db.client import get_connection  # the one-file adapter (ADR-008)

    with get_connection() as conn:
        counts = sync(conn, token, base_id, dry_run=args.dry_run)
    label = "fetched (dry run)" if args.dry_run else "synced"
    print(f"directory {label}: " + ", ".join(f"{k}={v}" for k, v in counts.items()))


if __name__ == "__main__":
    main()
